from config.settings import (
    APP_NAME, APP_ICON, APP_DESCRIPTION,
    DEFAULT_API_ENDPOINT, DEFAULT_TIMEOUT,
    MAX_REVISION_COUNT, EXAMPLE_TEXTS
)

__all__ = [
    'APP_NAME', 'APP_ICON', 'APP_DESCRIPTION',
    'DEFAULT_API_ENDPOINT', 'DEFAULT_TIMEOUT',
    'MAX_REVISION_COUNT', 'EXAMPLE_TEXTS'
]